name: Automatic Unit Testing

on:
  workflow_dispatch:
  push:
    branches:
    - main
    - 'main/*'
  pull_request:
    branches:
    - main
    - 'main/*'

jobs:
  test:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: Compilation & Build
      run: ./configure
      
    - name: Listing if file compiled correctly
      if: always()
      run: dir
      
    - name: Quick check
      if: always()
      run: ./main -x 100 -n 100 -d 100 -v 100
    
    - name: Testing with Set 1 parameters
      if: always()
      run: ./main -x 1000 -n 16777216 -d 1048576 -v 262144
      
    - name: Testing with Set 2 parameters
      if: always()
      run: ./main -x 1000 -n 16777216 -d 4194304 -v 1363148.8
      
    - name: Testing with Set 3 parameters
      if: always()
      run: ./main -x 5000 -n 1073741824 -d 1048576 -v 262144
      
    - name: Testing with Set 4 parameters
      if: always()
      run: ./main -x 500 -n 1073741824 -d 268435456 -v 67108864
