name: Makefile CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: Compilation & Build
      run: ./configure
    
    - name: Testing with Set 1 parameters
      run: ./main -x 1000 -n 16777216 -d 1048576 -v 262144
      
    - name: Testing with Set 2 parameters
      run: ./main -x 1000 -n 16777216 -d 4194304 -v 1363148.8
      
    - name: Testing with Set 3 parameters
      run: ./main -x 5000 -n 1073741824 -d 1048576 -v 262144
      
    - name: Testing with Set 4 parameters
      run: ./main -x 500 -n 1073741824 -d 268435456 -v 67108864
